import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { Container } from '@chakra-ui/react'
import Providers from './_components/Providers'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <Providers>
          <Container maxW="container.xl" p={0}>
            {children}
          </Container>
        </Providers>
      </body>
    </html>
  )
}
